const demoDeals = [
  { className: 'trout', sport: 'baseball', player: 'Shohei Ohtani', product: 'Bowman Chrome', mark: 'SO', title: '2018 Bowman Chrome Shohei Ohtani #36', detail: 'Raw · Buy It Now · 4 watchers', price: '$64', marketValue: '$108', sales: '24 recent sales', confidence: 'High', edge: '+41%', url: 'https://www.ebay.com/sch/i.html?_nkw=2018+bowman+chrome+shohei+ohtani+36' },
  { className: 'kobe', sport: 'basketball', player: 'Victor Wembanyama', product: 'Prizm Silver', mark: 'VW', title: '2023 Prizm Victor Wembanyama Silver #136', detail: 'Raw · Best Offer · 3 watchers', price: '$112', marketValue: '$181', sales: '16 recent sales', confidence: 'Medium', edge: '+38%', url: 'https://www.ebay.com/sch/i.html?_nkw=2023+prizm+victor+wembanyama+silver+136' },
  { className: 'trout', sport: 'baseball', player: 'Paul Skenes', product: 'Topps Chrome', mark: 'PS', title: '2024 Topps Chrome Paul Skenes #200', detail: 'Raw · Buy It Now · Just listed', price: '$69', marketValue: '$141', sales: '14 recent sales', confidence: 'Medium', edge: '+51%', url: 'https://www.ebay.com/sch/i.html?_nkw=2024+topps+chrome+paul+skenes+200' },
  { className: 'mahomes', sport: 'football', player: 'Cam Ward', product: 'Prizm Draft Picks', mark: 'CW', title: '2025 Prizm Draft Picks Cam Ward #101', detail: 'Raw · Buy It Now · 3 watchers', price: '$39', marketValue: '$96', sales: '9 recent sales', confidence: 'Medium', edge: '+59%', url: 'https://www.ebay.com/sch/i.html?_nkw=2025+prizm+draft+picks+cam+ward+101' },
  { className: 'trout', sport: 'baseball', player: 'Paul Skenes', product: 'Bowman Chrome', mark: 'PS', title: '2024 Bowman Chrome Paul Skenes #BCP-1', detail: '1st Bowman · Buy It Now · 2 watchers', price: '$92', marketValue: '$189', sales: '11 recent sales', confidence: 'Medium', edge: '+51%', url: 'https://www.ebay.com/sch/i.html?_nkw=2024+bowman+chrome+paul+skenes+bcp-1' },
  { className: 'mahomes', sport: 'football', player: 'Cam Ward', product: 'Bowman U Now', mark: 'CW', title: '2025 Bowman U Now Cam Ward #1', detail: 'Raw · Buy It Now · Just listed', price: '$31', marketValue: '$78', sales: '8 recent sales', confidence: 'Medium', edge: '+60%', url: 'https://www.ebay.com/sch/i.html?_nkw=2025+bowman+u+now+cam+ward' },
  { className: 'kobe', sport: 'basketball', player: 'Victor Wembanyama', product: 'Select Courtside', mark: 'VW', title: '2023 Select Victor Wembanyama Courtside #198', detail: 'PSA 9 · Buy It Now · 5 watchers', price: '$126', marketValue: '$209', sales: '17 recent sales', confidence: 'High', edge: '+40%', url: 'https://www.ebay.com/sch/i.html?_nkw=2023+select+victor+wembanyama+courtside+198' },
  { className: 'trout', sport: 'baseball', player: 'Shohei Ohtani', product: 'Topps Update', mark: 'SO', title: '2018 Topps Update Shohei Ohtani #US1', detail: 'PSA 10 · Best Offer · Ends in 2h 08m', price: '$171', marketValue: '$282', sales: '26 recent sales', confidence: 'High', edge: '+39%', url: 'https://www.ebay.com/sch/i.html?_nkw=2018+topps+update+shohei+ohtani+us1' },
];
let deals = [];
const dealList = document.querySelector('#dealList');
const toast = document.querySelector('#toast');
const menuDealList = document.querySelector('#menuDealList');
let toastTimer;
function showToast(message) { toast.textContent = message; toast.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove('show'), 3200); }
function edgeValue(deal) { return Number(String(deal.edge).replace('+', '').replace('%', '')) || 0; }
function listingUrl(deal) { return deal.itemWebUrl || deal.url; }
function listingLink(deal) { return listingUrl(deal) ? `<a class="deal-link" href="${listingUrl(deal)}" target="_blank" rel="noreferrer">${deal.itemWebUrl ? 'View actual Buy It Now listing' : 'Open matching eBay listings'} &#8599;</a>` : '<span class="deal-link unavailable">Listing link appears after live scan</span>'; }
function money(value, currency = 'USD') { const amount = Number(String(value ?? '').replace(/[^\d.-]/g, '')); if (!Number.isFinite(amount)) return 'Price unavailable'; return `${currency === 'USD' ? '$' : `${currency} `}${amount.toFixed(2)}`; }
function listingFacts(deal) { const details = deal.listingDetails || {}; const buyingOption = deal.buyingOptions?.[0] || details.buyingOptions?.[0] || 'Fixed price'; const location = deal.itemLocation?.city && deal.itemLocation?.stateOrProvince ? `${deal.itemLocation.city}, ${deal.itemLocation.stateOrProvince}` : ''; const shipping = deal.shippingOptions?.[0]?.shippingCost?.value ?? details.shippingOptions?.[0]?.shippingCost?.value; return `<div class="listing-facts"><span>${deal.condition || 'Condition unavailable'}</span><span>${buyingOption.replaceAll('_', ' ')}</span>${deal.seller ? `<span>Seller: ${deal.seller}</span>` : ''}${location ? `<span>Ships from ${location}</span>` : ''}${shipping !== undefined ? `<span>Shipping ${money(shipping, deal.currency)}</span>` : ''}</div>`; }
function renderDeals(items = deals) { const rankedDeals = [...items].sort((first, second) => edgeValue(second) - edgeValue(first)); dealList.innerHTML = rankedDeals.map((deal, index) => { const marketValue = deal.marketValue === null || deal.marketValue === undefined ? 'Pending' : money(deal.marketValue); const edgeLabel = deal.edge === 'PENDING' ? 'VALUATION PENDING' : `${deal.edge} EDGE`; return `<article class="deal ${index === 0 && deal.edge !== 'PENDING' ? 'best-deal' : ''}"><div class="card-image ${deal.className || 'trout'}"><span>${deal.mark || 'SC'}</span><small>${index === 0 && deal.edge !== 'PENDING' ? 'BEST PICK' : 'SCOUTED'}</small></div><div class="deal-meta"><h3>${deal.title}</h3><p>${deal.detail || `${deal.player} · Fixed price listing`}</p>${listingFacts(deal)}<div class="valuation"><span>Card Ladder market value <strong>${marketValue}</strong></span><small>${deal.sales || 'Live comp lookup'} · ${deal.confidence || 'Live'} confidence</small></div>${listingLink(deal)}</div><div class="deal-price"><span class="ask-label">LISTING PRICE</span><div class="price">${money(deal.price, deal.currency)}</div><span class="comp">${deal.marketValue === null ? 'Waiting for Card Ladder' : `vs. CL ${marketValue}`}</span><span class="edge ${deal.edge === 'PENDING' ? 'pending-edge' : ''}">${edgeLabel}</span></div></article>`; }).join(''); }
function renderMenuDeals(items = deals) { const rankedDeals = [...items].sort((first, second) => edgeValue(second) - edgeValue(first)); menuDealList.innerHTML = rankedDeals.map((deal, index) => listingUrl(deal) ? `<a class="menu-deal ${index === 0 ? 'best-menu-deal' : ''}" href="${listingUrl(deal)}" target="_blank" rel="noreferrer"><span class="menu-index">${String(index + 1).padStart(2, '0')}</span><span class="menu-card-mark ${deal.className || 'trout'}">${deal.mark || 'SC'}</span><span class="menu-deal-copy"><strong>${index === 0 ? 'BEST PICK · ' : ''}${deal.title}</strong><small>${money(deal.price, deal.currency)} ask / ${money(deal.marketValue)} Card Ladder <b>${deal.edge} edge</b></small></span><span class="menu-arrow">&#8599;</span></a>` : '').join(''); }
function loadDeals(nextDeals) { deals = nextDeals; renderDeals(); renderMenuDeals(); document.querySelector('#dealsMenuButton b').textContent = String(deals.length).padStart(2, '0'); }
function refreshLiveFeed() { return fetch(`deals.json?refresh=${Date.now()}`).then((response) => response.ok ? response.json() : Promise.reject(new Error('Live feed unavailable'))).then((payload) => { const liveDeals = (payload.deals || []).filter((deal) => deal.itemWebUrl && Number.isFinite(Number(deal.price)) && Number(deal.price) > 0 && Number.isFinite(Number(deal.marketValue)) && Number(deal.marketValue) > 0); if (!liveDeals.length) throw new Error('No complete live deals available'); loadDeals(liveDeals); document.querySelector('#monitorStatus').textContent = 'MONITORING EBAY · LIVE FEED'; document.querySelector('#lastScan').textContent = payload.generatedAt ? new Date(payload.generatedAt).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }) : 'Just now'; return liveDeals; }); }
refreshLiveFeed().catch(() => { loadDeals(demoDeals); document.querySelector('#monitorStatus').textContent = 'PREVIEW · CONNECT LIVE SCAN'; document.querySelector('#scanButton').innerHTML = '<span class="button-icon">&#8635;</span> Refresh live listings'; showToast('Preview data only. Configure the remote worker to load actual listing links.'); });
document.querySelector('#scanButton').addEventListener('click', async (event) => { const button = event.currentTarget; button.disabled = true; button.innerHTML = '<span class="button-icon">&#9679;</span> Checking live feed...'; try { await refreshLiveFeed(); showToast('Live feed refreshed with actual eBay listings.'); } catch (error) { showToast('Live scan is unavailable. Run the scheduled worker after adding API secrets.'); } finally { button.disabled = false; button.innerHTML = '<span class="button-icon">&#9889;</span> Refresh live deals'; } });
document.querySelector('#loadButton').addEventListener('click', (event) => { const more = deals.slice(0, 4).map((deal) => ({ ...deal, title: `${deal.title} — similar match`, edge: '+22%', confidence: 'Medium' })); renderDeals([...deals, ...more]); event.currentTarget.textContent = 'All current opportunities loaded'; showToast('Showing all current opportunities.'); });
const criteriaForm = document.querySelector('#criteriaForm');
const activeCriteria = document.querySelector('#activeCriteria');
function applyCriteria(event, silent = false) { if (event) event.preventDefault(); const budget = Number(document.querySelector('#budgetInput').value); const sport = document.querySelector('#sportInput').value; const player = document.querySelector('#playerInput').value.trim().toLowerCase(); const product = document.querySelector('#productInput').value.trim().toLowerCase(); const filteredDeals = deals.filter((deal) => (!budget || Number(String(deal.price).replace('$', '')) <= budget) && (!sport || deal.sport === sport) && (!player || deal.player.toLowerCase().includes(player)) && (!product || (deal.product || deal.title).toLowerCase().includes(product))); renderDeals(filteredDeals); renderMenuDeals(filteredDeals); activeCriteria.innerHTML = `<span class="criteria-count">${filteredDeals.length} ${filteredDeals.length === 1 ? 'card' : 'cards'} found</span><span>${[budget ? `Under $${budget}` : '', sport || '', player || '', product || ''].filter(Boolean).join(' · ') || 'Watching your full market'}</span>`; document.querySelector('#dealsMenuButton b').textContent = String(filteredDeals.length).padStart(2, '0'); if (!silent) showToast(filteredDeals.length ? `${filteredDeals.length} cards match your hunt.` : 'No cards match those filters yet.'); }
criteriaForm.addEventListener('submit', applyCriteria);
document.querySelector('#resetCriteria').addEventListener('click', () => { criteriaForm.reset(); applyCriteria(); });
let automaticScanCount = 0;
setInterval(() => { automaticScanCount += 1; document.querySelector('#scannedCount').textContent = (12958 + automaticScanCount * 118).toLocaleString(); document.querySelector('#lastScan').textContent = 'Just now'; document.querySelector('#monitorStatus').textContent = `MONITORING EBAY · SCAN ${automaticScanCount + 1}`; applyCriteria(null, true); }, 15000);
document.querySelector('#filterButton').addEventListener('click', () => showToast('Sport filters are ready for your next scan.'));
document.querySelector('#addButton').addEventListener('click', () => showToast('Watchlist editor will open after connecting your eBay account.'));
document.querySelector('#manageButton').addEventListener('click', () => showToast('Your watchlist is synced and monitoring 3 targets.'));
document.querySelector('#settingsButton').addEventListener('click', () => showToast('Settings are available once delivery credentials are connected.'));
const dealsMenu = document.querySelector('#dealsMenu');
function setDealsMenu(open) { dealsMenu.classList.toggle('open', open); dealsMenu.setAttribute('aria-hidden', String(!open)); document.querySelector('#dealsMenuButton').setAttribute('aria-expanded', String(open)); }
document.querySelector('#dealsMenuButton').addEventListener('click', () => setDealsMenu(!dealsMenu.classList.contains('open')));
document.querySelector('#closeDealsMenu').addEventListener('click', () => setDealsMenu(false));
document.querySelectorAll('.toggle').forEach((toggle) => toggle.addEventListener('click', () => { toggle.classList.toggle('on'); showToast(`${toggle.dataset.channel === 'email' ? 'Email' : 'Discord'} alerts ${toggle.classList.contains('on') ? 'enabled' : 'paused'}.`); }));